### ISSUE TITLE
Server工程打开后报错

### ISSUE THREAD

**Issue by JourneyHans** [JiepengTan/Lockstep-Tutorial#5]
请问这个是还需要添加什么配置吗？工程之间的引用也是丢失了的
The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

**Comment by xiaolangfensi** [comment]
下载.NET Core2.2的库

**Comment by xiaolangfensi** [comment]
> 请问这个是还需要添加什么配置吗？工程之间的引用也是丢失了的
> The current .NET SDK does not support targeting .NET Core 2.2. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

提示的很清楚了，下载.NET Core 2.2的库

**Comment by JourneyHans** [comment]
> > 请问这个是还需要添加什么配置吗？工程之间的引用也是丢失了的
> > The current .NET SDK does not support targeting .NET Core 2.2. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.
> 
> 提示的很清楚了，下载.NET Core 2.2的库

谢谢回复，我这边下载了还是不行，我重新建了个工程导入了一遍就可以了。

**Comment by jinq0123** [comment]
项目->属性->目标框架：
选 .Net Core 3.0 试试。
因为低版本都没安装。
